### ISSUE TITLE
`brew install` error message on `--help`

### ISSUE THREAD

**Issue by ihgann** [boz/kail#29]
Hi, just wanted to note that I see the following error when I run `--help`.

```shell
> kail --help
usage: kail [<flags>] <command> [<args> ...]

Tail for kubernetes pods

Flags:
  -h, --help                  Show context-sensitive help (also try --help-long and --help-man).
      --ignore=SELECTOR ...   ignore selector
  -l, --label=SELECTOR ...    label
  -p, --pod=NAME ...          pod
  -n, --ns=NAME ...           namespace
      --svc=NAME ...          service
      --rc=NAME ...           replication controller
      --rs=NAME ...           replica set
      --ds=NAME ...           daemonset
  -d, --deploy=NAME ...       deployment
      --node=NAME ...         node
      --ing=NAME ...          ingress
      --context=CONTEXT-NAME  kubernetes context
  -c, --containers=NAME ...   containers
      --dry-run               print matching pods and exit
      --log-file=/dev/stderr  log file output
      --log-level=error       log level
      --since=DURATION        Display logs generated since given duration, like 5s, 2m, 1.5h or
                              2h45m. Defaults to 1s.
      --glog-v="0"            glog -v value
      --glog-vmodule=""       glog -panic: template: usage:30:53: executing "usage" at <
>: write /dev/stderr: resource temporarily unavailable

goroutine 1 [running]:
github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).writeUsage(0xc4202700f0, 0xc420113680, 0x0, 0x0)
	/home/travis/gopath/src/github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:235 +0x11b
github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).maybeHelp(0xc4202700f0, 0xc420113680)
	/home/travis/gopath/src/github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:249 +0xd0
github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc4202700f0, 0xc42000a090, 0x1, 0x1, 0xc4202700f0, 0x1d2d9fb, 0x7, 0x1d39aed)
	/home/travis/gopath/src/github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin.v2/app.go:213 +0x18a
github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin%2ev2.Parse(0x1d2d9fb, 0x7)
	/home/travis/gopath/src/github.com/boz/kail/vendor/gopkg.in/alecthomas/kingpin.v2/global.go:37 +0x77
main.main()
	/home/travis/gopath/src/github.com/boz/kail/cmd/kail/main.go:88 +0x113
```

I installed via homebrew on my Mac.

Versions:

* macOS Mojave v10.14.2
* `brew` version `1.9.3-102-g058274a`
* `kail` version `0.7.0 (62372338c90a53d48566a637c5afbed4c9926452)`

**Comment by ihgann** [comment]
I should note - the app works fine as far as I can tell, it just shows this error message.
